services:
  user_managment:
    build:
      context: ./backend/backend_services/user_managment
      dockerfile: Dockerfile
    container_name: user_managment
    env_file:
      - ./backend/backend_services/user_managment/.env
    ports:
      - "3000:3000"
    volumes:
      - profile_images:/app/profile_images
      - user_managment_database:/app/database
  friendship:
    build:
      context: ./backend/backend_services/friendship
      dockerfile: Dockerfile
    container_name: friendship
    env_file:
      - ./backend/backend_services/friendship/.env
    ports:
      - "3001:3000"
    volumes:
      - friendship_database:/app/database










volumes:
  user_managment_database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoss/ft_transcendence/others/db_data/user_managment_database
  friendship_database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoss/ft_transcendence/others/db_data/friendship_database
  profile_images:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoss/ft_transcendence/others/profile_images
