services:
  user_managment:
    build:
      context: ./backend/backend_services/user_managment
      dockerfile: Dockerfile
    container_name: user_managment
    env_file:
      - ./backend/backend_services/user_managment/.env
    ports:
      - "3000:3000"
    # volumes:
    #   - profile_images:/app/profile_images
  # friendship:
  #   build:
  #     context: ./backend/backend_services/friendship
  #     dockerfile: Dockerfile
  #   container_name: friendship
  #   env_file:
  #     - ./backend/backend_services/friendship/.env
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - logs:/app/logs











  # user_managment_database:
  #   image: postgres:latest
  #   container_name: user_managment_database
  #   env_file:
  #     - ./databases/user_managment_database/.env
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - user_managment_database:/var/lib/postgresql/data

  # friendship_database:
  #   image: postgres:latest
  #   container_name: friendship_database
  #   env_file:
  #     - ./databases/friendship_database/.env
  #   ports:
  #     - "5433:5433"
  #   volumes:
  #     - friendship_database:/var/lib/postgresql/data
  #   command: ["postgres", "-c", "port=5433"]

# volumes:
#   user_managment_database:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/yoss/ft_transcendence/others/db_data/user_managment_database
  # friendship_database:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/yoss/ft_transcendence/others/db_data/friendship_database
  # private_key:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/yoss/ft_transcendence/others/RSA-key/private_key
  # public_key:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/yoss/ft_transcendence/others/RSA-key/public_key
  # logs:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/yoss/ft_transcendence/others/logs
  # profile_images:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/yoss/ft_transcendence/others/profile_images