FROM kibana:8.17.3

USER root

RUN apt-get update && apt-get install -y gosu

COPY --chown=kibana:kibana kibana.yml /usr/share/kibana/config/kibana.yml

COPY --chown=kibana:kibana script.sh /usr/local/bin/script.sh

RUN chmod 750 /usr/local/bin/script.sh

EXPOSE 5601

USER kibana

ENTRYPOINT ["/usr/local/bin/script.sh"]
