version: '3.8'
services:
#   nginx-modsecurity:
#     image: "nginx-modsecurity:app"
#     container_name: nginx-modsecurity
#     build: ./nginx-modsecurity/.
#     ports:
#       - "443:443"
#     networks:
#       - appNet
#     restart: always
#     depends_on:
#       - vault
  vault:
    image: "vault:app"
    container_name: vault
    build: ./vault/.
    hostname: vault 
    env_file:
      - .env
    networks:
      - appNet
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    restart: always

networks:
  appNet:
    driver: bridge
