FROM elasticsearch:8.17.3

USER root

RUN apt-get update && apt-get install -y gosu

# Set the working directory
WORKDIR /usr/share/elasticsearch

COPY first-setup.sh /usr/share/elasticsearch/first-setup.sh
COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# Ensure the script has execution permissions
RUN chmod +x /usr/share/elasticsearch/first-setup.sh

# Run Elasticsearch normally, but execute first-setup.sh before starting
ENTRYPOINT ["/usr/share/elasticsearch/first-setup.sh"]