FROM logstash:8.17.3

COPY logstash.yml /usr/share/logstash/config/logstash.yml

COPY ./logstash.conf /usr/share/logstash/pipeline/logstash.conf

WORKDIR /usr/share/logstash

ENTRYPOINT ["logstash", "-f", "/usr/share/logstash/pipeline/logstash.conf"]